### ISSUE TITLE
PHPStan is now required in production code

### ISSUE THREAD

**Issue by mfuehrer82** [php-static-analysis/phpstan-extension#1]
Hi Carlos,

I think you should add a warning to the Readme that PHPStan becomes a requirement in production code.
I think this is the reason why static analysis tools like PHPStan does not have made this transition to attributes yet. It 's the same with PHPUnit. There are attributes, but, these are for TestContext. 
Adding PHPStan or other static analysers to production code brings up a risk. This should be mentioned in the Readme of this package.

What do you think?

**Comment by jackwh** [comment]
You can install the attributes first, then require the extension as a dev dependency:

1. `composer require php-static-analysis/attributes`
2. `composer require php-static-analysis/phpstan-extension --dev`

That should let you use them in production without PHPStan.

(As an aside, what exactly is the risk of PHPStan in production? I know it's not best practice, but surely as a static analysis tool it produces no side effects so is no riskier than any other package. Is that not the case?)

**Comment by carlos-granados** [comment]
@mfuehrer82 the fact that the `composer.json` file lists PHPStan in its "require" section does not mean that it will be installed in production. It just means that this library needs PHPStan to work, not only to develop it. But, as @jackwh mentioned, if you install this library as a dev dependency, then PHPStan will not be installed in production

Closing this issue, thanks for your interest
